# Conclusion
Below are the main takeaways from our study of Montgomery County Car Crash Data (2015-2023):

1. **Collision Hotspots**: The most common sites for car accidents are County and Maryland roads.
2. **Time Patterns**: We observe most accidents in May and October. We also observe that weekdays have more crashes than weekends, with rush hours at 8 am and 5 pm on weekdays, and afternoons on weekends. This suggests crash frequency correlates with commuting patterns.
3. **Collision Causes**: Alcohol is the most commonly detected substance in car accidents. Around ⅓ of the substance abuse including all categories cause collision. Driver distraction plays a role in 18% of accidents, while vehicle equipment issues are a minor factor. In addition, vehicles in motion suffer the most severe damage. 
4. **Environmental Impacts**: Car accidents happen most frequently at traffic signals or in uncontrolled areas. Crashes at higher speed limits usually result in more serious damage. The worst damage occurs when adverse weather meets wet roads. Additionally, statistical analysis shows clear links between various environmental factors and the severity of injuries and the vehicle damage extent.  
5. **Vehicle Conditions**: Older and lighter vehicles tend to suffer more damage in crashes.

Our study is mainly limited by the dataset itself, which contains unverified information. And we're missing some key details from our dataset for our research questions, such as that in one of the problems where we try to identify the causes of the crashes, 25.17% of the data associated with Driver Substance Abuse is unknown. For future directions, we want to investigate more diverse geographics if there’s accessible data and run more thorough statistical analysis to establish scientific rigorous findings. Through this project, our key learnings include establishing interesting questions from a raw dataset, handling missing data, performing time series analysis, creating interactive data visualization with D3, and creating an interactive HTML based report. 

**Technical notes**:
Feel free to explore the data using our [code](https://github.com/TomlandHilarious/edav-final-project). 
