# Interactive graph

<style>
  * {
    font-family: sans-serif;
  }
</style> 

<div id="plot">
</div>

<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
<script src="scripts/myscript.js"></script>

<h1>Explore Different Environmental Factors on Car Crash Severity</h1>
<h4>"Choose your environmental factor and severity measure and explore their relationship!"</h4>


<h5>
Steps:
</h5>
<p>
1. Choose the type of environmental factor you are interested in using <span style="border: 1px solid blue; font-weight: bold;">Independent Variable</span> dropdown button. You can select from Weather, Speed Limit, Surface Condition, Light and Traffic Control. <br>
2. Choose the type of car crash severity measure you are interested in using <span style="border: 1px solid blue; font-weight: bold;">Dependent Variable</span>. You can select from Injury Severity and Vehicle Damage Extent.<br>
3. Select the two levels of the environmental factors you want to compare using <span style="border: 1px solid blue; font-weight: bold;">Chosen level 1</span> and <span style="border: 1px solid blue; font-weight: bold;">Chosen level 2</span>. <br>
4. Hover over a bar to view detailed information about percentage of collision severity measure at that level. <br>
5. Choose your combinations to explore our results for Q4: Environmental Factors!
</p>


<div>
 <label style="color: darkblue; font-weight: bold; font-size: 12;">Independent Variable:</label>
    <select id="independentDropdown">
      <option value="Weather">Weather</option>
      <option value="Surface.Condition">Surface Condition</option>
      <option value="Light">Light</option>
      <option value="Traffic.Control">Traffic Control</option>
      <option value="Speed.Limit">Speed Limit</option>
  </select>
</div>
<div>
 <label style="color: darkblue; font-weight: bold; font-size: 12;">Dependent Variable:</label>
  <select id="dependentDropdown">
    <option value="Injury.Severity">Injury Severity</option>
    <option value="Vehicle.Damage.Extent">Vehicle Damage Extent</option>
  </select>
</div>
<div>
 <label style="color: darkblue; font-weight: bold; font-size: 12;">Chosen Level 1:</label>
  <select id="chosenindependent">
    <option >NONE</option>
  </select>
  </div>
<div>
 <label style="color: darkblue; font-weight: bold; font-size: 12;">Chosen Level 2:</label>
  <select id="chosendependent">
    <option >NONE</option>
  </select>
</div>

<div id="leftGraph"></div>
<div id="rightGraph"></div> 

<h5>
Remember: 
</h5>
<p>
 - The top graph refers to the distribution of the collision situation for environmental factor level 1; the bottom graph refers to the distribution of the collision situation for environmental factor level 2.<br>
 - <span style="border: 1px solid blue; font-weight: bold;">Total Count</span> in top right corner is represent the total traffic collision in Montgomery County from 2015 to 2023. <br>
 - Everytime you change the environmental factor, re-select the levels you are interested. 
</p>
