# Results

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
library(dplyr)
library(ggplot2)
library(forcats)
library(tidyr)
library(lubridate)
library(stringr)

data <- read.csv("data/Crash_Reporting_-_Drivers_Data.csv", header = TRUE, sep=",",na.strings=c("","N/A"))
data_q1 = data |> select(Route.Type,Cross.Street.Type)
data_q2 = data |> select(Crash.Date.Time)
data_q3 = data |> select(Driver.Substance.Abuse,Driver.Distracted.By,
                         Vehicle.Movement,Equipment.Problems,
                         Injury.Severity,Vehicle.Damage.Extent)
data_q4 = data |> select(Weather,Surface.Condition,Light,
                         Traffic.Control,Speed.Limit,
                         Injury.Severity,Vehicle.Damage.Extent)
data_q5 = data |> select(Vehicle.Body.Type,Vehicle.Year,
                         Vehicle.Make,Vehicle.Damage.Extent)
```

## Q1

```{r}
# Change Variables as factors
data_q1$Route.Type =  as.factor(data_q1$Route.Type) |> 
  fct_explicit_na("NA")
data_q1$Cross.Street.Type = as.factor(data_q1$Cross.Street.Type) |> 
  fct_explicit_na("NA")

# ggplot(data_q1, aes(y = fct_relevel(fct_rev(fct_infreq(Route.Type)), 
#                                     "NA"))) +
#   geom_bar(fill = "cornflowerblue") +
#   labs(x = "Number of Crashes", 
#        y = "Route Type", 
#        title = "Number of Crashes by Route Types") +
#   theme_light()
# 
# ggplot(data_q1, aes(y = fct_relevel(fct_rev(fct_infreq(Cross.Street.Type)), 
#                                     "NA"))) +
#   geom_bar(fill = "cornflowerblue") +
#   labs(x = "Number of Crashes",
#        y = "Cross Street Type",
#        title = "Number of Crashes by Cross Street Types") +
#   theme_light()
```

```{r}
data_q1$id = rownames(data_q1)
data_q1 = pivot_longer(data_q1,cols=Route.Type:Cross.Street.Type)
ggplot(data_q1,aes(y = fct_relevel(fct_rev(fct_infreq(value)), 
                                    "NA"), fill = name)) +
  geom_bar(position = "dodge") +
  labs(x = "Number of Crashes",
       y = "Types",
       title = "Number of Crashes by Route Types and Cross Street Types") +
  theme_light()
```

## Q2

```{r}
data_q2$Crash.Date.Time = mdy_hms(data_q2$Crash.Date.Time)
data_q2$Year = as.factor(year(data_q2$Crash.Date.Time))
data_q2$Month = as.factor(months(data_q2$Crash.Date.Time)) |> 
  fct_relevel("January","February","March","April","May","June","July",
              "August","September","October","November","December")
data_q2$Day = as.factor(day(data_q2$Crash.Date.Time))
data_q2$Weekday = as.factor(weekdays(data_q2$Crash.Date.Time)) |> 
  fct_relevel("Sunday","Monday","Tuesday","Wednesday","Thursday",
              "Friday","Saturday")
data_q2$Hours = as.factor(hour(data_q2$Crash.Date.Time))

# ggplot(data_q2,aes(x = Year)) +
#   geom_point(stat = "count") +
#   geom_line(aes(group = 1), stat = "count", color = "cornflowerblue") +
#   ggtitle("Number of Crashes by Year") +
#   theme_light()
# 
# ggplot(data_q2,aes(x = Month)) +
#   geom_point(stat = "count") +
#   geom_line(aes(group = 1), stat = "count", color = "cornflowerblue") +
#   ggtitle("Number of Crashes by Month") +
#   theme_light()

# ggplot(data_q2,aes(x = Day)) +
#   geom_point(stat = "count") +
#   geom_line(aes(group = 1), stat = "count", color = "cornflowerblue") +
#   ggtitle("Number of Crashes by Day") +
#   theme_light()

# ggplot(data_q2,aes(x = Weekday)) +
#   geom_point(stat = "count") +
#   geom_line(aes(group = 1), stat = "count", color = "cornflowerblue") +
#   ggtitle("Number of Crashes by Weekday") +
#   theme_light()
# 
# ggplot(data_q2,aes(x = Hours)) +
#   geom_point(stat = "count") +
#   geom_line(aes(group = 1), stat = "count", color = "cornflowerblue") +
#   ggtitle("Number of Crashes by Hours") +
#   theme_light()

```

```{r, fig.width=12, fig.height=8}
ggplot(data_q2, aes(Hours)) +
  geom_point(stat = "count") + 
  geom_density(aes(group = 1), stat = "count", color = "cornflowerblue") +
  facet_wrap(~Weekday, ncol = 7) +
  labs(y = "Number of Crashes", 
       title = "Total Number of Crashes Per Hour Faceted by Weekday from 2015-2023") +
  theme_light() +
  theme(axis.text.x = element_text(size = 6, angle = 45),
         plot.title = element_text(hjust = 0.5)) +
  scale_x_discrete(labels = function(x) str_sub(x, 1, 3))
  
```

```{r, fig.width=12, fig.height=8}
ggplot(data_q2,aes(Month)) +
  geom_point(stat = "count") +
  geom_density(aes(group = 1), stat = "count", color = "cornflowerblue") +
  facet_wrap(~Year,ncol = 9) +
  labs(y = "Number of Crashes", 
       title = "Number of Crashes Per Month Faceted by Year from 2015-2023") +
  theme_light() +
  theme(axis.text.x = element_text(size = 6, angle = 45),
         plot.title = element_text(hjust = 0.5)) +
  scale_x_discrete(labels = function(x) str_sub(x, 1, 3))
```

## Q3

```{r}
summary(data_q3)
```

```{r}
data_q3$Driver.Substance.Abuse = as.factor(data_q3$Driver.Substance.Abuse) |> 
  fct_explicit_na("NA")
data_q3$Driver.Distracted.By = as.factor(data_q3$Driver.Distracted.By) |> 
  fct_explicit_na("NA")
data_q3$Vehicle.Movement = as.factor(data_q3$Vehicle.Movement) |> 
  fct_explicit_na("NA")
data_q3$Equipment.Problems = as.factor(data_q3$Equipment.Problems) |> 
  fct_explicit_na("NA")
```

## Q4


```{r, fig.width=12, fig.height=7}
library(vcd)
library(dplyr)
library(RColorBrewer)

# Since OTHER and UNKNOWN do not provide information of interest for our questions, we drop these two levels from
# our analysis for Vehile damage extent
data_q4_regrouped <- data_q4 %>%
  mutate(
    Weather = case_when(
      Weather %in% c("CLEAR", "CLOUDY") ~ "CLEAR",
      TRUE ~ "ADVERSE"
    ),
    Surface.Condition = case_when(
      Surface.Condition %in% c("DRY") ~ "DRY",
      Surface.Condition %in% c("WET", "WATER(STANDING/MOVING)") ~ "WET",
      Surface.Condition %in% c("ICE", "SLUSH", "SNOW") ~ "SNOW/ICE",
      Surface.Condition %in% c("MUD, DIRT, GRAVEL", "SAND", "OIL", "OTHER", "UNKNOWN") ~ "OTHERS",
      TRUE ~ Surface.Condition 
    )
  ) 
data_q4_regrouped$Vehicle.Damage.Extent <- factor(data_q4_regrouped$Vehicle.Damage.Extent, 
                                                   levels = c("UNKNOWN","OTHER", "NO DAMAGE", "SUPERFICIAL", "FUNCTIONAL", "DISABLING", "DESTROYED"))
data_q4_filtered <- data_q4_regrouped %>%
  filter(!Vehicle.Damage.Extent %in% c("UNKNOWN", "OTHER"))
data_q4_filtered$Vehicle.Damage.Extent <- droplevels(data_q4_filtered$Vehicle.Damage.Extent)
# mosaic(Vehicle.Damage.Extent ~ Surface.Condition,
#       rot_labels=c(45, 0),
#       direction =c('v','h'),
#       data_q4_filtered
#       )
# mosaic(Vehicle.Damage.Extent ~ Weather,
#       rot_labels=c(0, 0),
#       direction =c('v','h'),
#       data_q4_filtered
#       )
mosaic(Vehicle.Damage.Extent ~  Weather + Surface.Condition,
      rot_labels=c(0, 45, 45, 45),
      direction =c('v', 'v', 'h'),
      data_q4_filtered
      ) 
```


```{r, fig.width=13, fig.height=7}
# top coding, group 55 and 55+ together due to small number for 60, 65, 70, 75
data_q4_speed <- data_q4 %>%
  mutate(
    Speed.Limit = case_when(
      Speed.Limit >= 55 ~ "55+",
      TRUE ~  as.character(Speed.Limit)
    ),
  ) 
data_q4_speed$Vehicle.Damage.Extent <- factor(data_q4_speed$Vehicle.Damage.Extent, 
                                                   levels = c("UNKNOWN","OTHER", "NO DAMAGE", "SUPERFICIAL", "FUNCTIONAL", "DISABLING", "DESTROYED"))
data_q4_speed$Speed.Limit <- factor(data_q4_speed$Speed.Limit,
                                    levels = c("0", "5", "10", "15", "20", "25", "30", "35",
                                               "40", "45", "50", "55+"))
data_q4_speed$Injury.Severity <- factor(data_q4_speed$Injury.Severity, 
                                                   levels = c("NO APPARENT INJURY", "POSSIBLE INJURY",
                                                              "SUSPECTED MINOR INJURY", 
                                                              "SUSPECTED SERIOUS INJURY", "FATAL INJURY"))
data_q4_filtered <- data_q4_speed %>%
  filter(!Vehicle.Damage.Extent %in% c("UNKNOWN", "OTHER"))
data_q4_filtered$Vehicle.Damage.Extent <- droplevels(data_q4_filtered$Vehicle.Damage.Extent)
# speed-limit with vehicle damage extent
mosaic(Vehicle.Damage.Extent ~ Speed.Limit,
      rot_labels=c(45, 0),
      direction =c('v','h'),
      data_q4_filtered
      )
# speed-limit with injury-severity
# mosaic(Injury.Severity ~ Speed.Limit,
#        rot_labels=c(45, 45),
#        direction=c('v', 'h'),
#        data_q4_filtered) 

```




```{r, fig.width=13,fig.height=7}
theme_heat <- theme_classic() +
  theme(axis.line = element_blank(),
        axis.ticks = element_blank(),
        axis.text.x = element_text(angle = 15, vjust = 0.5, size = 5.5),
        strip.text = element_text(size = 8),
        plot.title = element_text(hjust = 0.5)
        )
lighting_order <- c("DAWN", "DAYLIGHT", "DUSK", "DARK LIGHTS ON", "DARK -- UNKNOWN LIGHTING", 
                  "DARK NO LIGHTS", "OTHER", "UNKNOWN")
injury_order <- rev(c("NO APPARENT INJURY", "POSSIBLE INJURY", "SUSPECTED MINOR INJURY", "SUSPECTED SERIOUS INJURY", "FATAL INJURY"))
mydata <- data_q4 %>%
  filter(!is.na(Speed.Limit) & !is.na(Traffic.Control) & !is.na(Injury.Severity)) %>%
  select(Light, Traffic.Control, Injury.Severity) %>%
  group_by(Light, Traffic.Control, Injury.Severity) %>%
  summarize(Frequency = n())
# View the new dataframe
mydata$Light <- factor(mydata$Light, levels=lighting_order)
mydata$Injury.Severity <- factor(mydata$Injury.Severity, levels=injury_order)
mydata3 <- mydata |> group_by(Injury.Severity, Light) |> 
  mutate(Total = sum(Frequency)) |> ungroup()

ggplot(mydata3, aes(x = Light, y = Traffic.Control)) +
  geom_tile(aes(fill = (Frequency/Total)), color = "white") +
  coord_fixed() + 
  scale_fill_gradient2(low = "black", mid = "white",
                        high = "red", midpoint = 0.1) +
  facet_wrap(~Injury.Severity) + theme_heat +
  labs(title="Heatmap for Light and Traffic Control Conditions Under Different Injury Levels")
  
```
```{r}
vehicle_damage_table_1 <- xtabs(~ Vehicle.Damage.Extent + Surface.Condition, data = data_q4_filtered)
vehicle_damage_table_2 <- xtabs(~ Vehicle.Damage.Extent + Weather, data = data_q4_filtered)
vehicle_damage_table_3 <- xtabs(~ Vehicle.Damage.Extent + Traffic.Control, data = data_q4_filtered)
vehicle_damage_table_4 <- xtabs(~ Vehicle.Damage.Extent + Light, data = data_q4_filtered)
vehicle_damage_table_5 <- xtabs(~ Vehicle.Damage.Extent + Speed.Limit, data = data_q4_filtered )
injury_severity_table_1 <- xtabs(~ Injury.Severity + Surface.Condition, data = data_q4_filtered)
injury_severity_table_2 <- xtabs(~ Injury.Severity + Weather, data = data_q4_filtered)
injury_severity_table_3 <- xtabs(~ Injury.Severity + Traffic.Control, data = data_q4_filtered)
injury_severity_table_4 <- xtabs(~ Injury.Severity + Light, data = data_q4_filtered)
injury_severity_table_5 <- xtabs(~ Injury.Severity + Speed.Limit, data = data_q4_filtered )
# chi-q test Vehicle.Damage.Extent vs. Surface.Condition
# summary(vehicle_damage_table_1)
# # chi-q test Vehicle.Damage.Extent vs. Weather
# summary(vehicle_damage_table_2)
# summary(vehicle_damage_table_3)
# summary(vehicle_damage_table_4)
# summary(vehicle_damage_table_5)
# summary(injury_severity_table_1)
# summary(injury_severity_table_2)
# summary(injury_severity_table_3)
# summary(injury_severity_table_4)
# summary(injury_severity_table_5)
```



